services:
  - type: web
    name: taverna-infiniti-service
    runtime: node
    plan: free
    buildCommand: corepack enable && pnpm install --frozen-lockfile && pnpm build
    startCommand: pnpm start
    healthCheckPath: /
    autoDeployTrigger: commit
    envVars:
      - key: NODE_ENV
        value: production
      - key: HOSTNAME
        value: 0.0.0.0
