services:
  - type: web
    name: taverna-infiniti-service
    runtime: static
    buildCommand: npm install && npm run build
    staticPublishPath: out
    pullRequestPreviewsEnabled: false
    autoDeployTrigger: commit
    headers:
      - path: /*
        name: Cache-Control
        value: public, max-age=3600
